version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: resturant
    restart: always
    environment:
      POSTGRES_DB: resturant
      POSTGRES_USER: resturant
      POSTGRES_PASSWORD: resturant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: